### Create a Booking and Trigger MPESA Payment
POST http://localhost:3000/api/bookings/create
Content-Type: application/json

{
  "userId": "7d882998-cbe2-4e8a-af8f-2abe3695c3e0",
  "eventId": "d1244b99-d6f3-46c2-97ae-a7f41823b3ed",
  "ticketType": "VIP",
  "quantity": 1
}

### Get Bookings by User
GET http://localhost:3000/api/bookings/7d882998-cbe2-4e8a-af8f-2abe3695c3e0
Content-Type: application/json

### Get a Booking by ID
GET http://localhost:3000/api/bookings/5a54159c-42e6-4018-8fa8-bd34a31fd8ef
Content-Type: application/json

### Cancel a Booking
DELETE http://localhost:3000/api/bookings/6a62099e-1282-4680-ac39-a5060827921d
Content-Type: application/json

### Update a Booking
PUT http://localhost:3000/api/bookings/update/0da452c9-1f24-4988-a2ce-d64de6a89ba0
Content-Type: application/json

{
  "newQuantity": 1,
  "newTicketType": "Single"
}

### Get Bookings for a Specific Event
GET http://localhost:3000/api/bookings/event/24cf38ea-f45a-4ccf-a680-72de404c3f5b

