### Create a Booking
POST http://localhost:3000/api/bookings/create
Content-Type: application/json

{
  "userId": "7d882998-cbe2-4e8a-af8f-2abe3695c3e0",
  "eventId": "9f3810f4-f919-4338-80f1-4e7e585b4814",
  "ticketType": "Group of 5",
  "quantity": 3
}

### Get Bookings by User
GET http://localhost:3000/api/bookings/7d882998-cbe2-4e8a-af8f-2abe3695c3e0
Content-Type: application/json

### Get a Booking by ID
GET http://localhost:3000/api/bookings/5a54159c-42e6-4018-8fa8-bd34a31fd8ef
Content-Type: application/json

### Cancel a Booking
DELETE http://localhost:3000/api/bookings/5a54159c-42e6-4018-8fa8-bd34a31fd8ef
Content-Type: application/json

### Update a booking
PUT http://localhost:3000/api/bookings/update/21de62ef-54c0-4d4e-b764-e177370c6c13
Content-Type: application/json

{
  "newQuantity": 5,
  "newTicketType": "Single"
}

### Get bookings for a specific event
GET http://localhost:3000/api/bookings/event/9f3810f4-f919-4338-80f1-4e7e585b4814

