### Create an Event
POST http://localhost:3000/api/events/create
Content-Type: application/json

{
  "eventName": " tbdeleted",
  "date": "2025-09-15T10:00:00.000Z",
  "time": "10:00 AM",
  "location": "Chuka, Kenya",
  "description": "An event for chuka comrades to have fun",
  "image": "https://i.pinimg.com/474x/7a/29/df/7a29dfc903d98c6ba13b687ef1fa1d1a.jpg",
  "totalTickets": 100
}

### Get All Events
GET http://localhost:3000/api/events/

### Get a Single Event by ID
GET http://localhost:3000/api/events/7404b8f8-11e6-41c9-b821-a1878cc46ef2
### Update an Event
PUT http://localhost:3000/api/events/1d1d021e-8be1-4285-b747-dfda98b9cafa
Content-Type: application/json

{
  "eventName": "Updated Raha rAVE DELETE Event",
  "date": "2025-10-20T10:00:00.000Z",
  "time": "11:00 AM",
  "location": "Mombasa, Kenya",
  "description": "An updated RnB event.",
  "totalTickets": 100
}

### Delete an Event
DELETE http://localhost:3000/api/events/7404b8f8-11e6-41c9-b821-a1878cc46ef2
