### Create an Event
POST http://localhost:3000/api/events/create
Content-Type: application/json

{
  "eventName": "Raha tbdeleted",
  "date": "2025-09-15T10:00:00.000Z",
  "time": "10:00 AM",
  "location": "Chuka, Kenya",
  "description": "An event for chuka comrades to have fun",
  "totalTickets": 500
}

### Get All Events
GET http://localhost:3000/api/events/

### Get a Single Event by ID
GET http://localhost:3000/api/events/9f3810f4-f919-4338-80f1-4e7e585b4814
### Update an Event
PUT http://localhost:3000/api/events/fe976351-a6df-4131-8112-65365b46c849
Content-Type: application/json

{
  "eventName": "Updated Tech Conference",
  "date": "2025-10-20T10:00:00.000Z",
  "time": "11:00 AM",
  "location": "Mombasa, Kenya",
  "description": "An updated tech event.",
  "totalTickets": 600
}

### Delete an Event
DELETE http://localhost:3000/api/events/fe976351-a6df-4131-8112-65365b46c849
