###Get notifications
GET http://localhost:3000/api/notifications/7d882998-cbe2-4e8a-af8f-2abe3695c3e0

###Mark notification as read
PUT http://localhost:3000/api/notifications/3e34d47c-c949-4758-8512-da7fdca4d782/read
