### Create a new ticket for an event
POST http://localhost:3000/api/tickets/create
Content-Type: application/json

{
  "eventId": "fb84b54a-0a14-407d-8d73-91c68734e4b9",
  "type": "Single",
  "quantity": 100,
  "price": 1.00
}

### Update a ticket by ID
PUT http://localhost:3000/api/tickets/update/82749b45-557d-4469-890a-72656c410cdc
Content-Type: application/json

{
  "type": "Single",
  "quantity": 300,
  "price": 100.00
}

### Delete a ticket by ID
DELETE http://localhost:3000/api/tickets/delete/eab4c9ee-ac13-448a-beeb-884a0737a1d6

### Fetch all tickets for a specific event
GET http://localhost:3000/api/tickets/event/9f3810f4-f919-4338-80f1-4e7e585b4814

### Fetch a single ticket by ID
GET http://localhost:3000/api/tickets/b951a73d-a4a2-4e57-adb3-1fd59bd23c5d
