### Create a new ticket for an event
POST http://localhost:3000/api/tickets/create
Content-Type: application/json

{
  "eventId": "d1244b99-d6f3-46c2-97ae-a7f41823b3ed",
  "type": "Single",
  "quantity": 50,
  "price": 1.00
}

### Update a ticket by ID
PUT http://localhost:3000/api/tickets/update/8e67efea-dfe2-4a6b-9460-9e52850344f7
Content-Type: application/json

{
  "type": "Single",
  "quantity": 300,
  "price": 1.00
}

### Delete a ticket by ID
DELETE http://localhost:3000/api/tickets/delete/eab4c9ee-ac13-448a-beeb-884a0737a1d6

### Fetch all tickets for a specific event
GET http://localhost:3000/api/tickets/event/8e67efea-dfe2-4a6b-9460-9e52850344f7

### Fetch a single ticket by ID
GET http://localhost:3000/api/tickets/b951a73d-a4a2-4e57-adb3-1fd59bd23c5d
