### Register a new user
POST http://localhost:3000/api/users/register
Content-Type: application/json

{
  "firstName": "Carol",
  "lastName": "Martin",
  "phoneNo": "011199679",
  "email": "carolmartoz1063@gmail.com",
  "password": "password123456"
}

### Login user
POST http://localhost:3000/api/users/login
Content-Type: application/json

{
  "email": "carolmartoz1063@gmail.com",
  "password": "password123456"
}

### Get user by ID 
GET http://localhost:3000/api/users/7d882998-cbe2-4e8a-af8f-2abe3695c3e0

### Get all users
GET http://localhost:3000/api/users

###Update user
PUT http://localhost:3000/api/users/8aa9e673-8348-4380-9041-61ed5080315c
Content-Type: application/json

{
  "firstName": "UpdatedFirstName",
  "lastName": "UpdatedLastName",
  "phoneNo": "0987654321",
  "email": "updatedemail@example.com",
  "password": "NewSecurePassword"
}

###Delete user
DELETE http://localhost:3000/api/users/8aa9e673-8348-4380-9041-61ed5080315c

