### Register a new user
POST http://localhost:3000/api/users/register
Content-Type: application/json

{
  "firstName": "Carol",
  "lastName": "Doe",
  "phoneNo": "4323456690",
  "email": "caroldoe@example.com",
  "password": "examplepassword"
}

### Login user
POST http://localhost:3000/api/users/login
Content-Type: application/json

{
  "email": "caroldoe@example.com",
  "password": "examplepassword"
}

### Get user by ID 
GET http://localhost:3000/api/users/066d05e2-0886-4496-9d4a-5ec90023adc7

### Get all users
GET http://localhost:3000/api/users

###Update user
PUT http://localhost:3000/api/users/066d05e2-0886-4496-9d4a-5ec90023adc7
Content-Type: application/json

{
  "firstName": "UpdatedFirstName",
  "lastName": "UpdatedLastName",
  "phoneNo": "0987654321",
  "email": "updatedemail@example.com",
  "password": "NewSecurePassword"
}

###Delete user
DELETE http://localhost:3000/api/users/066d05e2-0886-4496-9d4a-5ec90023adc7

